In [17]:
import pandas as pd

In [18]:
df = pd.read_csv('/home/karthikmsd/sem9/20XW92-SOFTWARE-TESTING/ca1practice/testcases1.csv')

In [19]:
df.tail()

,Test Case,Input Password,Expected Result
0,Password length less than 6,abc,Invalid - Password length less than 6
1,Password length exactly 6,abcdef,Valid - Password length exactly 6
2,Password length between 7 and 11,abcdefg,Valid - Password length between 7 and 11
3,Password length exactly 12,abcdefghijk,Valid - Password length exactly 12
4,Password length more than 12,abcdefghijklm,Invalid - Password length more than 12

In [20]:
def password_screening(password):
    if len(password) < 6:
        return "Invalid - Password length less than 6"
    elif len(password) > 12:
        return "Invalid - Password length more than 12"
    elif len(password) == 6:
        return "Valid - Password length exactly 6"
    elif len(password) == 12:
        return "Valid - Password length exactly 12"
    else:
        return f"Valid - Password length between 7 and 11"

In [21]:
df["Performed Result"] = df["Input Password"].apply(password_screening)
df["Match"] = df["Expected Result"] == df["Performed Result"]

In [22]:
df

,Test Case,Input Password,Expected Result,Performed Result,Match
0,Password length less than 6,abc,Invalid - Password length less than 6,Invalid - Password length less than 6,True
1,Password length exactly 6,abcdef,Valid - Password length exactly 6,Valid - Password length exactly 6,True
2,Password length between 7 and 11,abcdefg,Valid - Password length between 7 and 11,Valid - Password length between 7 and 11,True
3,Password length exactly 12,abcdefghijk,Valid - Password length exactly 12,Valid - Password length between 7 and 11,False
4,Password length more than 12,abcdefghijklm,Invalid - Password length more than 12,Invalid - Password length more than 12,True

In [23]:
# 2

In [41]:
df = pd.read_csv('/home/karthikmsd/sem9/20XW92-SOFTWARE-TESTING/ca1practice/testcases2.csv')

In [42]:
df

   Test Case  Purchase Value Expected Result            Test Type
0          0            1.00     No discount       Lower boundary
1          1           50.00     No discount       Upper boundary
2          2           51.00     5% discount       Lower boundary
3          3          200.00     5% discount       Upper boundary
4          4          201.00    10% discount       Lower boundary
5          5          500.00    10% discount       Upper boundary
6          6          501.00    15% discount       Lower boundary
7          7           50.01     5% discount  Just above boundary
8          8          200.99    10% discount  Just below boundary
9          9          500.01    15% discount  Just above boundary

In [43]:
def calculate_discount(purchase_value):
    if purchase_value <= 50:
        return 'No discount'
    elif 50 < purchase_value <= 200:
        return '5% discount'
    elif 200 < purchase_value <= 500:
        return '10% discount'
    else:
        return '15% discount'

In [44]:
df['Actual Result'] = df['Purchase Value'].apply(calculate_discount)
df['Result Matches'] = df['Actual Result'] == df['Expected Result']

In [45]:
df

,Test Case,Purchase Value,Expected Result,Test Type,Actual Result,Result Matches
0,0,1.00,No discount,Lower boundary,No discount,True
1,1,50.00,No discount,Upper boundary,No discount,True
2,2,51.00,5% discount,Lower boundary,5% discount,True
3,3,200.00,5% discount,Upper boundary,5% discount,True
4,4,201.00,10% discount,Lower boundary,10% discount,True
5,5,500.00,10% discount,Upper boundary,10% discount,True
6,6,501.00,15% discount,Lower boundary,15% discount,True
7,7,50.01,5% discount,Just above boundary,5% discount,True
8,8,200.99,10% discount,Just below boundary,10% discount,True
9,9,500.01,15% discount,Just above boundary,15% discount,True