In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/home/karthikmsd/sem9/20XW92-SOFTWARE-TESTING/ca1practice/testcases2.csv')

In [3]:
df

,Test Case,Order Value,Expected Result,Equivalence Class
0,1,5,Success message,Valid Range (1 to 10)
1,2,0,"Error message: ""Invalid Order""",Invalid Range Below 1
2,3,50,"Error message: ""Only 10 Pizza can be ordered""",Invalid Range Above 10
3,4,100,"Error message: ""Invalid Order""",Invalid Three-Digit Numbers

In [5]:
def order_pizza(pizza_count):
    if pizza_count < 1:
        return 'Error message: "Invalid Order"'
    elif 1 <= pizza_count <= 10:
        return 'Success message'
    elif 11 <= pizza_count <= 99:
        return 'Error message: "Only 10 Pizza can be ordered"'
    elif pizza_count >= 100:
        return 'Error message: "Invalid Order"'

In [6]:
df['Actual Result'] = df['Order Value'].apply(order_pizza)

df['Result Matches'] = df['Actual Result'] == df['Expected Result']

In [7]:
df

,Test Case,Order Value,Expected Result,Equivalence Class,Actual Result,Result Matches
0,1,5,Success message,Valid Range (1 to 10),Success message,True
1,2,0,"Error message: ""Invalid Order""",Invalid Range Below 1,"Error message: ""Invalid Order""",True
2,3,50,"Error message: ""Only 10 Pizza can be ordered""",Invalid Range Above 10,"Error message: ""Only 10 Pizza can be ordered""",True
3,4,100,"Error message: ""Invalid Order""",Invalid Three-Digit Numbers,"Error message: ""Invalid Order""",True